logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 101.43.21.132:27001
        - 101.43.21.132:27002
        - 101.43.21.132:27003